set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(__warnings "-Wall -Wextra -Wpedantic -Wshadow")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g -DNDEBUG ${__warnings}")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_DEBUG "-Og -g ${__warnings}")
